---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateAILogger
      azure.rm.apimanagementlogger:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        logger_id: myLogger
        logger_type: applicationInsights
        description: adding a new logger
        credentials:
          instrumentationKey: 714c6d94-e036-4d07-8b0b-979f4b63bc65
    - name: ApiManagementCreateDiagnostic
      azure.rm.apimanagementdiagnostic:                                                                                         
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        diagnostic_id: applicationinsights
        always_log: allErrors
        logger_id: /loggers/myLoggerId
        sampling:
          sampling_type: fixed
          percentage: '50'
        frontend:
          request:
            headers:
              - Content-type
            body:
              bytes: '512'
          response:
            headers:
              - Content-type
            body:
              bytes: '512'
        backend:
          request:
            headers:
              - Content-type
            body:
              bytes: '512'
          response:
            headers:
              - Content-type
            body:
              bytes: '512'
    - name: ApiManagementCreateApiDiagnostic
      azure.rm.apimanagementapidiagnostic:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        diagnostic_id: applicationinsights
        always_log: allErrors
        logger_id: /loggers/myLoggerId
        sampling:
          sampling_type: fixed
          percentage: '50'
        frontend:
          request:
            headers:
              - Content-type
            body:
              bytes: '512'
          response:
            headers:
              - Content-type
            body:
              bytes: '512'
        backend:
          request:
            headers:
              - Content-type
            body:
              bytes: '512'
          response:
            headers:
              - Content-type
            body:
              bytes: '512'