---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateProduct
      azure.rm.apimanagementproduct:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
        display_name: Test Template ProductName
        pstate: published
    - name: ApiManagementCreateProductApi
      azure.rm.apimanagementproductapi:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
        api_id: "{{ api_name }}"
        path: newapiPath
    - name: ApiManagementCreateProductPolicy
      azure.rm.apimanagementproductpolicy:                                                                                      
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
        policy_id: policy
        value: "<policies>\r\n  <inbound />\r\n  <backend>\r\n    <forward-request />\r\n  </backend>\r\n  <outbound />\r\n</policies>"
        format: xml
    - name: ApiManagementCreateProductGroup                                                                                   
      azure.rm.apimanagementproductgroup:                                                                                       
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
        group_id: myGroup
        display_name: EchoApi
