---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateTag
      apimanagementtag:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        tag_id: myTag
        display_name: tag1
